swagger: "2.0"
info:
  title: MyCustomer
  description: MyCustomer app does stuff
  version: 1.0.0

basePath: /v1/
consumes:
  - application/json
produces:
  - application/json


paths:
  /hello:
    get:
      tags: [Greet User]
      operationId: endpoints.user.greetings.greet
      summary: Says hello <name>
      description: Greets the user whose name is supplied. If no name, greets world.
      produces:
        - application/json
      parameters:
        - name: name
          in: query
          type: string
          required: false
      responses:
        200:
          description: Greeting successfully sent
          schema:
            $ref: '#/definitions/Greeting'
        401:
          description: Authentication failed
        440:
          description: Session expired, login again
        404:
          description: User does not exist

  /user/all:
    get:
      tags: [List User]
      operationId: endpoints.user.list.get
      summary: Return list of users
      description: Return a list of all users in the database.
      produces:
        - application/json
      responses:
        200:
          description: Retrieved User List successfully
          schema:
            $ref: '#/definitions/List'
        401:
          description: Authentication failed
        440:
          description: Session expired, login again


definitions:
  Greeting:
    type: string
    # items:
    #   type: object
    #   properties:
    #     id:
    #       type: integer
    #     datetime:
    #       type: string
    #     user:
    #       type: string
    #     content:
    #       type: string

  List:
    type: array
    # items:
    #   type: object
    #   properties:
    #     id:
    #       type: integer
    #     datetime:
    #       type: string
    #     user:
    #       type: string
    #     content:
    #       type: string
